### ISSUE TITLE
Lanyrd API proxy is down

### ISSUE THREAD

**Issue by aron** [asyncjs/asyncjs.github.com#82]
Seems the server is down, http://lanyrd.asyncjs.com

@premasagar where was this hosted? On nodejitsu? Is there any way to kickstart it again?

**Comment by premasagar** [comment]
Oh, I'll give it a nudge. If any of the current async crew want to manage a
new server, let me know.

-- 
*Premasagar Rose*
premasagar.com
dharmafly.com
twitter.com/premasagar
github.com/premasagar

**Comment by premasagar** [comment]
Oh hang on. I forgot - I already passed it on to @chrisnewtn, who manages
the proxy. Such foresight.

Chris - can you kick it? (yes you can)


-- 
*Premasagar Rose*
premasagar.com
dharmafly.com
twitter.com/premasagar
github.com/premasagar

**Comment by larister** [comment]
Closing this as I'm guessing @chrisnewtn doesn't have time, plus there's a chance we might move to a metalsmith based website soon
